.TH "Cjt_especies" 3 "Dv Mai 15 2020" "Version 15/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_especies \- Representa un conjunt d'espècies ordenades alfabèticament\&.  

.SH SYNOPSIS
.br
.PP
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBCjt_especies\fP ()"
.br
.RI "Crea un conjunt d'espècies buit\&. "
.ti -1c
.RI "void \fBcrea_especie\fP (const string &id, const string &gen)"
.br
.RI "Crea una espècie i la introdueix al conjunt\&. "
.ti -1c
.RI "void \fBelimina_especie\fP (const string &id)"
.br
.RI "Elimina la espècie indicada del conjunt d'espècies\&. "
.ti -1c
.RI "bool \fBexisteix_especie\fP (const string &id) const"
.br
.RI "Consulta si existeix la espècie indicada\&. "
.ti -1c
.RI "double \fBcalcular_distancia\fP (const string &id, const string &id2) const"
.br
.RI "Consulta la distàncie entre dues espècies\&. "
.ti -1c
.RI "void \fBobtener_gen\fP (const string &id) const"
.br
.RI "Consulta el gen de la espècie demanada\&. "
.ti -1c
.RI "bool \fBfinal\fP ()"
.br
.RI "Consulta si l'iterador del mapa del conjunt d'especies apunta al final d'ell o no\&. "
.ti -1c
.RI "void \fBinicio\fP ()"
.br
.RI "Posiciona l'iterador del mapa del conjunt d'especies apuntant al primer element\&. "
.ti -1c
.RI "void \fBactual\fP (string &act)"
.br
.RI "El paràmetre explícit passa a tenir la informació del element apuntat pel iterador actual\&. "
.ti -1c
.RI "void \fBavanza\fP ()"
.br
.RI "Avança la posició del iterador en una posició;\&. "
.ti -1c
.RI "void \fBlee_cjt_especies\fP ()"
.br
.RI "Lectura d'un conjunt d'espècies\&. "
.ti -1c
.RI "void \fBimprime_cjt_especies\fP () const"
.br
.RI "Escriptura del conjunt d'espècies\&. "
.ti -1c
.RI "void \fBtabla_distancias\fP () const"
.br
.RI "Escriu una taula de les distàncies entre espècies\&. "
.in -1c
.SS "Mètodes Privats"

.in +1c
.ti -1c
.RI "void \fBelimina_especie_tabla_dist\fP (const string &id)"
.br
.RI "Actualitza la taula de distàncies si s'elimina una espècie\&. "
.ti -1c
.RI "void \fBafegeix_especie_tabla_dist\fP (const string &id)"
.br
.RI "Actualitza la taula de distàncies si s'afegeix una espècie\&. "
.in -1c
.SS "Atributs Privats"

.in +1c
.ti -1c
.RI "map< string, \fBEspecie\fP > \fBcjt_especies\fP"
.br
.RI "Mapa on guardem les espècies del conjunt d'espècies\&. "
.ti -1c
.RI "map< string, map< string, double > > \fBtaula_distancies\fP"
.br
.RI "Nested map\&. Mapa on guardem les distancies entre les espècies\&. "
.ti -1c
.RI "map< string, \fBEspecie\fP >::const_iterator \fBit\fP"
.br
.RI "Iterator\&. Iterador del mapa d'especies\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Representa un conjunt d'espècies ordenades alfabèticament\&. 

Ofereix la possibilitat de calcular distàncies entre diferents especies i modificar el conjunt, ja sigui creant noves especies o eliminant\&. Es pot consultar el gen d'una especie i si una especie existeix\&.També inclou la possibilitat d'imprimir una taula de distancies entre especies\&. 
.PP
Definició a la línia 27 del fitxer Cjt_especies\&.hh\&.
.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "Cjt_especies::Cjt_especies ()"

.PP
Crea un conjunt d'espècies buit\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat és un conjunt d'especies buit\&. 
.RE
.PP

.PP
Definició a la línia 11 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
11                            {
12 // Mètode constructor d'especie\&. Posem el mapa d'especies i el nested map de la taula
13 // de distàncies com a dos mapes buits\&.
14   Cjt_especies::cjt_especies = map<string, Especie> ();
15   Cjt_especies::taula_distancies = map<string,map<string,double>>();
16 }
.fi
.SH "Documentació de les Funcions Membre"
.PP 
.SS "void Cjt_especies::elimina_especie_tabla_dist (const string & id)\fC [private]\fP"

.PP
Actualitza la taula de distàncies si s'elimina una espècie\&. 
.PP
\fBPrecondició\fP
.RS 4
La espècie la qual es vol eliminar existeix dins la taula de distàncies\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha actualitzat la taula\&. 
.RE
.PP

.PP
Definició a la línia 196 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
196                                                               {
197   //Es posiciona un iterador apuntant a la posició de l'id demanat\&.
198   map<string,map<string,double>>::const_iterator it = Cjt_especies::taula_distancies\&.find(id);
199   //Es posiciona un iterador apuntant a la primera posició del mapa de distancies\&.
200   //Inv: Farà tantes iteracions fins que l'iterador sigui igual al primer que hem buscat\&. Així ens
201   //estalviem bucles innecessaris\&. Aquest bucle elimina la especie demanada del map interior\&.
202   for (map<string,map<string,double>>::iterator it2 = Cjt_especies::taula_distancies\&.begin(); it2 != it; ++it2) {
203       it2->second\&.erase(it2->second\&.find(id));
204     }
205   //Eliminem la especie del mapa gran de la taula de distancies\&.
206   Cjt_especies::taula_distancies\&.erase(it);
207 }
.fi
.SS "void Cjt_especies::afegeix_especie_tabla_dist (const string & id)\fC [private]\fP"

.PP
Actualitza la taula de distàncies si s'afegeix una espècie\&. 
.PP
\fBPrecondició\fP
.RS 4
La espècie la qual es vol afegir existeix no existeix dins la taula de distàncies\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha actualitzat la taula\&. 
.RE
.PP

.PP
Definició a la línia 211 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
211                                                               {
212   //Es posiciona un iterador apuntant a la taula d'especies, a la posició on esta el id demanat\&.
213   map<string,Especie>::const_iterator esp = Cjt_especies::cjt_especies\&.find(id);
214   //Es crea un map auxiliar on s'aniran ficant les distancies\&.
215   map<string, double> aux;
216   //Inv: Recorregut del mapa, de principi a final\&. 
217   for (map<string,Especie>::const_iterator it = Cjt_especies::cjt_especies\&.begin(); it != Cjt_especies::cjt_especies\&.end(); ++it) {
218     map<string,map<string,double>>::iterator itt = Cjt_especies::taula_distancies\&.find(it->first);
219     //Calcula la distancia entre dues especies, la que entra pel parametre explícit
220     //i la que apunta el iterador\&.
221     double x = it->second\&.distancia(esp->second);
222     //If per fer les operacions si el identificador està a la part baixa
223     // i per tant només es fica una distancia al map interior\&.
224     if (id > it->first) {
225       itt->second\&.insert(make_pair(id, x));
226     }
227     //If per fer les operacions si l'identificador està a la part alta i s'ha
228     //de crear un nou map amb totes les altres especies\&.
229     else if (id < it->first) {
230       aux\&.insert(make_pair(it->first, x));
231     }
232       
233   }
234   //Finalment insertem el mapa a la taula de distancies\&.
235   Cjt_especies::taula_distancies\&.insert(make_pair(id, aux));
236 
237 }
.fi
.SS "void Cjt_especies::crea_especie (const string & id, const string & gen)"

.PP
Crea una espècie i la introdueix al conjunt\&. 
.PP
\fBPrecondició\fP
.RS 4
No existeix cap espècie amb el mateix identificador\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha creat una espècie\&. 
.RE
.PP

.PP
Definició a la línia 23 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
23                                                                   {
24 // Entren dos paràmetres explícits\&. El primer paràmetre és la clau
25 // del mapa\&. El valor d'aquesta clau serà una especie la qual es genera
26 // amb la constructora d'especie mitjançant un gen\&. A més, aquesta especie
27 // s'introdueix a la taula de distancies mitjançant el mètode afegeix
28 // especie tabla dist\&.
29       Especie e(gen);
30       Cjt_especies::cjt_especies\&.insert(make_pair(id,e));
31       afegeix_especie_tabla_dist(id);
32 }
.fi
.SS "void Cjt_especies::elimina_especie (const string & id)"

.PP
Elimina la espècie indicada del conjunt d'espècies\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
La espècie s'ha eliminat del paràmetre implícit\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP id 
.RE
.PP

.PP
Definició a la línia 38 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
38                                                    {
39 // S'elimina la espècie indicada pel paràmetre explícit\&.
40 // Es busca la espècie mitjaçant un iterador del mapa d'especies
41 // i s'elimina la espècie indicada\&.
42 // Observació: Aquesta funció no comprova si existeix una espècie 
43 // o no, per tant, s'ha de fer compravació prèvia amb la funció
44 // Cjt_especie::existe_especie(id)\&.
45     map<string, Especie>::const_iterator it = Cjt_especies::cjt_especies\&.find(id);
46     Cjt_especies::cjt_especies\&.erase(it);
47     Cjt_especies::elimina_especie_tabla_dist(id);     
48 }
.fi
.SS "bool Cjt_especies::existeix_especie (const string & id) const"

.PP
Consulta si existeix la espècie indicada\&. 
.PP
\fBPrecondició\fP
.RS 4
El id és un string vàlid\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat indica si existèix la espècie dins el conjunt d'espècies\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP id 
.RE
.PP
\fBRetorna\fP
.RS 4
bool 
.RE
.PP

.PP
Definició a la línia 51 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
51                                                           {
52 // Es consulta si existeix la espècie dins el map d'especies\&.
53 // Es busca la especie mitjançant un iterador\&. En el cas que
54 // l'iterador apuntes al final de mapa, la especie no existeix 
55 // i es retorna false, en cas contrari retorna true\&.
56   map<string, Especie>::const_iterator it = Cjt_especies::cjt_especies\&.find(id);
57   if (it != Cjt_especies::cjt_especies\&.end()) return true;
58   return false;
59 }
.fi
.SS "double Cjt_especies::calcular_distancia (const string & id, const string & id2) const"

.PP
Consulta la distàncie entre dues espècies\&. 
.PP
\fBPrecondició\fP
.RS 4
Les dues espècies existeixen al conjunt\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
Et retorna la distància entre dues espècies\&. Excepcions: Si retorna -1 vol dir que les dues espècies no existèixen dins el conjunt d'especies\&. Si retorna -2 vol dir que la espècie id no existeix dins el conjunt d'especies\&. Si retorna -3 vol dir que la espècie id2 no existeix dins el conjunt d'especies\&.
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP id1 
.br
\fIstring\fP id2 
.RE
.PP
\fBRetorna\fP
.RS 4
double 
.RE
.PP

.PP
Definició a la línia 62 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
62                                                                                  {
63 // Retorna la distància entre dues especies\&.
64 // Es fan comprovación abans de consultar-les\&. En el cas
65 // que no existeixin les dues espècies es retorna un -1\&.
66 // Si no existeix només la primera espècie retorna un -2\&.
67 // Si no existeix només la segona espècie retorna un -3\&.
68 // En cas que les dues especies existeixin, és fan unes comprovacions:
69 //    Com el map només calcula les distàncies necessaries ja que 
70 //    Distancia (a,b) = Distancia (b,a), el map ordena les distancies
71 //    per ordre alfabètic amb la seva clau\&. Per tant hem de tenir en 
72 //    compte que si es consulta distancia c a\&. No podem consultar de 
73 //    primeres\&. Per tant, amb dos iteradors mirem si apuntent al final,
74 //    En el cas que passés, cambien d'ordre els iteradors i aquests
75 //    accedeixen a la posició on hi ha la distància demanada\&.
76 // Observació: Aquesta funció no calcula les distàncies, sinó consulta
77 // el mapa de distàncies\&.  
78   if (not Cjt_especies::existeix_especie(id) and not Cjt_especies::existeix_especie(id2)) return -1; 
79   else if (not Cjt_especies::existeix_especie(id)) return -2;
80   else if (not Cjt_especies::existeix_especie(id2)) return -3;
81   else {
82       map<string,map<string,double>>::const_iterator it = Cjt_especies::taula_distancies\&.find(id);
83       map<string,double>::const_iterator it2 = it->second\&.find(id2);
84       if (it2 == it->second\&.end()) {
85         it = Cjt_especies::taula_distancies\&.find(id2);
86         it2 = it->second\&.find(id);
87         return it2->second;
88       }
89       return it2->second;
90     }
91 }
.fi
.SS "void Cjt_especies::obtener_gen (const string & id) const"

.PP
Consulta el gen de la espècie demanada\&. 
.PP
\fBPrecondició\fP
.RS 4
La espècie existeix al conjunt d'espècies\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha mostrat el gen de la espècie\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP 
.RE
.PP
\fBRetorna\fP
.RS 4
string 
.RE
.PP

.PP
Definició a la línia 95 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
95                                                      {
96 // Es consulta el gen d'una especie mitjançant una 
97 // funció de la classe Especie i un iterador\&.
98 // Observació: S'ha de comprovar prèviament que aquesta especie existeix\&.
99   map<string, Especie>::const_iterator it = Cjt_especies::cjt_especies\&.find(id);
100   cout << it->second\&.consultar_gen() << endl;
101   
102 }
.fi
.SS "bool Cjt_especies::final ()"

.PP
Consulta si l'iterador del mapa del conjunt d'especies apunta al final d'ell o no\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El booleà retorna cert si apunta al final del mapa\&. 
.RE
.PP

.PP
Definició a la línia 105 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
105                          {
106 // Es fa comprovacions si l'iterador de l'àmbit
107 // privat apunta al final del conjunt d'especies\&.
108 // Retorna cert si apunta al final, en cas contrari
109 // retorna fals\&.
110   return it == Cjt_especies::cjt_especies\&.end();
111 
112 }
.fi
.SS "void Cjt_especies::inicio ()"

.PP
Posiciona l'iterador del mapa del conjunt d'especies apuntant al primer element\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El iterador apunta al primer element del mapa\&. 
.RE
.PP

.PP
Definició a la línia 115 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
115                           {
116 // Es posiciona l'iterador de l'ambit
117 // privat apuntant a la primera posició 
118 // del mapa d'especies\&.
119   it = Cjt_especies::cjt_especies\&.begin();
120 }
.fi
.SS "void Cjt_especies::actual (string & act)"

.PP
El paràmetre explícit passa a tenir la informació del element apuntat pel iterador actual\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El paràmetre explícit passa a tenir la informació del element apuntat pel iterador actual 
.RE
.PP

.PP
Definició a la línia 123 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
123                                      {
124 // Es modifica el string del paràmetre 
125 // explícit i se li adjudica el string
126 // al qual apunta el iterador\&.
127   act = it->first;
128 }
.fi
.SS "void Cjt_especies::avanza ()"

.PP
Avança la posició del iterador en una posició;\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El iterador del mapa d'especies apunta una posició endavant\&. 
.RE
.PP

.PP
Definició a la línia 132 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
132                           {
133 // Es posiciona l'iterador de l'ambit
134 // privat apuntant a una posició més endavant 
135 // de la qua apuntava l'iterador abans\&.
136 // Observació: S'avançarà l'iterador sempre
137 // i quan l'iterador no estigui apuntant al final\&.
138   if (not final()){
139         ++Cjt_especies::it;
140 
141   }
142 }
.fi
.SS "void Cjt_especies::lee_cjt_especies ()"

.PP
Lectura d'un conjunt d'espècies\&. 
.PP
\fBPrecondició\fP
.RS 4
Estan preparats al canal estandar d'entrada un enter i les dades dels elements que llegirem\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El paràmetre implícit conté un conjunt d'especies llegits pel canal estàndar\&. 
.RE
.PP

.PP
Definició a la línia 148 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
148                                     {
149   //La condició de si es llegeix un nou conjunt
150   //d'especies es que es descarta el contingut previ\&.
151   //Per tant fem clear dels dos mapes\&.
152   Cjt_especies::taula_distancies\&.clear();
153   Cjt_especies::cjt_especies\&.clear();
154   //int que indica el nombre d'especies que es volen afegir\&.
155   int n;
156   cin >> n;
157   //Inv: el bucle for mai farà més de n iteracions\&. 
158   //A cada iteració farà una crida a la funció crea especie\&.
159   for (int i = 0; i < n; ++i) {
160     string id, gen;
161     cin >> id >> gen;
162     Cjt_especies::crea_especie(id,gen);
163   }
164 }
.fi
.SS "void Cjt_especies::imprime_cjt_especies () const"

.PP
Escriptura del conjunt d'espècies\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha escrit pel canal estàndar de sortida les espècies del paràmetre implícit\&. 
.RE
.PP

.PP
Definició a la línia 167 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
167                                               {
168   //Inv: És situa un iterador apuntant a la primera posició del
169   //mapa d'especies\&. Avançarà una iteració fins que el punter apunti al final\&.
170   //A cada iteració s'impreix una especie\&.
171   for (map<string,Especie>::const_iterator it = Cjt_especies::cjt_especies\&.begin(); it != Cjt_especies::cjt_especies\&.end(); ++it) {
172     cout << it->first << " ";
173     it->second\&.escriure();
174   }
175 }
.fi
.SS "void Cjt_especies::tabla_distancias () const"

.PP
Escriu una taula de les distàncies entre espècies\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha imprès la taula de distàncies\&. 
.RE
.PP

.PP
Definició a la línia 178 del fitxer Cjt_especies\&.cc\&.
.PP
.nf
178                                           {
179   //Inv: És situa un iterador apuntant a la primera posició del
180   //mapa de distancies\&. Avançarà una posició fins que el punter apunti al final\&.
181   //A cada iteració s'impreix un identificador de especie i s'executa un segon bucle\&.
182   for(map<string,map<string,double>>::const_iterator it = Cjt_especies::taula_distancies\&.begin(); it != Cjt_especies::taula_distancies\&.end(); ++it) {
183     cout << it->first << ":";
184     //Inv: És situa un iterador apuntant a la primera posició del
185     //map interior del map de distancies d'especies\&. Avançarà una posició fins que el punter apunti al final\&.
186     //A cada iteració s'impreix un identificador d'especie del map interior i la distancia respecte les dues especies\&.
187     for (map<string,double>::const_iterator it2 = it->second\&.begin(); it2 != it->second\&.end(); ++it2) {
188         cout << " " << it2->first << " (" << it2->second << ")"; 
189     }
190     cout << endl;
191   }
192 }
.fi
.SH "Documentació de les Dades Membre"
.PP 
.SS "map<string,\fBEspecie\fP> Cjt_especies::cjt_especies\fC [private]\fP"

.PP
Mapa on guardem les espècies del conjunt d'espècies\&. 
.PP
Definició a la línia 35 del fitxer Cjt_especies\&.hh\&.
.SS "map<string, map<string,double> > Cjt_especies::taula_distancies\fC [private]\fP"

.PP
Nested map\&. Mapa on guardem les distancies entre les espècies\&. 
.PP
Definició a la línia 39 del fitxer Cjt_especies\&.hh\&.
.SS "map<string, \fBEspecie\fP>::const_iterator Cjt_especies::it\fC [private]\fP"

.PP
Iterator\&. Iterador del mapa d'especies\&. 
.PP
Definició a la línia 58 del fitxer Cjt_especies\&.hh\&.

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
