.TH "Cjt_especies.hh" 3 "Dj Mai 14 2020" "Version 14/05/2020" "Creació d'un arbre filogenètic." \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_especies.hh \- Especificació de la classe \fBCjt_especies\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCjt_especies\fP"
.br
.RI "Representa un conjunt d'espècies ordenades alfabèticament\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Especificació de la classe \fBCjt_especies\fP\&. 


.PP
\fBAutor\fP
.RS 4
Xavier Coll Ribas 
.RE
.PP

.PP
Definició al fitxer \fBCjt_especies\&.hh\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. a partir del codi font\&.
