.TH "Cjt_clusters.hh" 3 "Dc Mai 20 2020" "Version v6.3 19/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_clusters.hh \- Especificació de la classe \fBCjt_clusters\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCjt_clusters\fP"
.br
.RI "Representa un conjunt de clusters\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Especificació de la classe \fBCjt_clusters\fP\&. 


.PP
\fBAutor\fP
.RS 4
Xavier Coll Ribas 
.RE
.PP

.PP
Definició al fitxer \fBCjt_clusters\&.hh\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
