.TH "Cjt_clusters.cc" 3 "Dv Mai 15 2020" "Version 15/05/2020" "Creació d'un arbre filogenètic." \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_clusters.cc \- Còdig de la classe \fBCjt_clusters\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripció Detallada"
.PP 
Còdig de la classe \fBCjt_clusters\fP\&. 


.PP
Definició al fitxer \fBCjt_clusters\&.cc\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. a partir del codi font\&.
