.TH "Cjt_clusters" 3 "Dv Mai 15 2020" "Version 15/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_clusters \- Representa un conjunt de clusters\&.  

.SH SYNOPSIS
.br
.PP
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBCjt_clusters\fP ()"
.br
.RI "Crea un conjunt de clusters buit\&. "
.ti -1c
.RI "double \fBdist_clust\fP (const string &id, const string &id2) const"
.br
.RI "Busca la distància entre els clusters demanats\&. "
.ti -1c
.RI "pair< string, string > \fBmin_dist\fP () const"
.br
.RI "Calcula la distancia mínima entre Clusters\&. "
.ti -1c
.RI "void \fBinicialitza_clusters\fP (\fBCjt_especies\fP &conjunt, const bool ve_de_func)"
.br
.RI "Inicialitza els clusters del conjunt\&. "
.ti -1c
.RI "void \fBejecuta_paso_wpgma\fP (const bool &a)"
.br
.RI "Fusiona els clusters que estan a menor distància\&. "
.ti -1c
.RI "void \fBimprime_cluster\fP (string id) const"
.br
.RI "Imprimeix el cluster indicat\&. "
.ti -1c
.RI "void \fBimprime_tabla_distancias\fP () const"
.br
.RI "Imprimeix la taula de distàncies entre clusters\&. "
.ti -1c
.RI "void \fBimprime_arbol_filogenetico\fP (\fBCjt_especies\fP &conjunt)"
.br
.RI "Imprimeix l'arbre filogenètic\&. "
.in -1c
.SS "Mètodes Privats"

.in +1c
.ti -1c
.RI "void \fBtabla_dist_clust\fP (const \fBCjt_especies\fP &conjunt)"
.br
.RI "Imprimeix el cluster indicat\&. "
.ti -1c
.RI "void \fBafegeix_especie_clusters\fP (const pair< string, string > &dist)"
.br
.RI "Afegeix la fusió dels dos clusters al mapa de clusters i a la taula de distancies\&. "
.ti -1c
.RI "void \fBelimina_especie_clusters\fP (const string &id)"
.br
.RI "Elimina la especie indicada del conjunt del mapa de clusters i de la taula de distàncies\&. "
.in -1c
.SS "Atributs Privats"

.in +1c
.ti -1c
.RI "map< string, \fBCluster\fP > \fBmap_clusters\fP"
.br
.RI "Mapa on es guarden els clusters resultants\&. La clau es un string i la dada un \fBCluster\fP\&. "
.ti -1c
.RI "map< string, map< string, double > > \fBtabla_distancias_cluster\fP"
.br
.RI "Nested map on es guarden les distancies entre clusters\&. És un nested map\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Representa un conjunt de clusters\&. 

Ofereix la possibilitat d'ajuntar clusters per tal d'anar creant l'arbre filogenètic\&. També pots demanar imprimir un cluster determinat si existeix i imprimir l'arbre resultant\&. També ofereix una taula de distancies entre clusters\&. Els clusters es generen mitjançant la sincronització amb un conjunt d'especies i es compleix amb la funció inicializa_clusters\&. 
.PP
Definició a la línia 77 del fitxer Cjt_clusters\&.hh\&.
.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "Cjt_clusters::Cjt_clusters ()"

.PP
Crea un conjunt de clusters buit\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat és un conjunt de clusters buit\&. 
.RE
.PP

.PP
Definició a la línia 16 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
16                            {
17     //Es crea el mapa de clusters i el de distancies buit\&.
18     map_clusters = map<string,Cluster>();
19     tabla_distancias_cluster = map<string,map<string,double>>();
20 }
.fi
.SH "Documentació de les Funcions Membre"
.PP 
.SS "void Cjt_clusters::tabla_dist_clust (const \fBCjt_especies\fP & conjunt)\fC [private]\fP"

.PP
Imprimeix el cluster indicat\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha passat totes les distancies entre especies al conjunt de clusters\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fI\fBCjt_especies\fP\fP Entra un objecte del tipus conjunt especies\&. 
.RE
.PP

.PP
Definició a la línia 143 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
143                                                                {
144     //Consulta mitjançant el conjunt de especies les distancies entre elles per 
145     //passar-les al conjunt de clusters\&.
146     for (map<string,Cluster>::const_iterator it = map_clusters\&.begin(); it != map_clusters\&.end(); ++it) {
147         map<string, double> aux;
148         for (map<string,Cluster>::const_iterator it2 = it; it2 != map_clusters\&.end(); ++it2) {
149             if (it->first != it2->first) { //Comprova que el iterador sigui diferent al segon iterador\&.
150             double x = conjunt\&.calcular_distancia(it->first, it2->first);
151             aux\&.insert(make_pair(it2->first, x));
152             }
153         }
154         tabla_distancias_cluster\&.insert(make_pair(it->first, aux));
155     }
156 }
.fi
.SS "void Cjt_clusters::afegeix_especie_clusters (const pair< string, string > & dist)\fC [private]\fP"

.PP
Afegeix la fusió dels dos clusters al mapa de clusters i a la taula de distancies\&. 
.PP
\fBPrecondició\fP
.RS 4
El pair no és buit\&. 
.br
 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha fusionat els clusters\&. 
.RE
.PP

.PP
Definició a la línia 159 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
159                                                                            {
160     //Aquí es modifica les distancies dels clusters fent servir
161     //la formula de WPGMA\&.
162     string fus = dist\&.first + dist\&.second;
163     map<string,map<string,double>>::const_iterator it = tabla_distancias_cluster\&.begin();
164     while (it != tabla_distancias_cluster\&.end() and it->first < fus) {
165         tabla_distancias_cluster[it->first][fus] = (tabla_distancias_cluster[it->first][dist\&.first] + tabla_distancias_cluster[min(it->first,dist\&.second)][max(it->first,dist\&.second)])/2;
166         ++it;
167     }
168     while (it != tabla_distancias_cluster\&.end()) {
169         tabla_distancias_cluster[fus][it->first] = (tabla_distancias_cluster[dist\&.first][it->first] + tabla_distancias_cluster[min(it->first,dist\&.second)][max(it->first,dist\&.second)])/2;
170         ++it;
171     }
172     map<string,Cluster>::const_iterator a = map_clusters\&.find(dist\&.first);
173     map<string,Cluster>::const_iterator b = map_clusters\&.find(dist\&.second);
174     Cluster c(a->second,b->second,dist_clust(dist\&.first,dist\&.second));
175     map_clusters\&.insert(make_pair(fus,c));
176 
177 
178 }
.fi
.SS "void Cjt_clusters::elimina_especie_clusters (const string & id)\fC [private]\fP"

.PP
Elimina la especie indicada del conjunt del mapa de clusters i de la taula de distàncies\&. 
.PP
\fBPrecondició\fP
.RS 4
La especie a eliminar existeix\&. 
.br
 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha eliminat la especie del mapa de clusters i la taula de distancies\&. 
.RE
.PP

.PP
Definició a la línia 182 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
182                                                             {
183     //Es posiciona un iterador apuntant a la posició de l'id demanat\&. El nom de l'iterador era per donar humor al còdig\&.
184     map<string, Cluster>::const_iterator it_peix = map_clusters\&.find(id);
185   map_clusters\&.erase(it_peix);
186     //Es posiciona un iterador apuntant a la posició de l'id demanat\&. 
187   map<string,map<string,double>>::const_iterator it = tabla_distancias_cluster\&.find(id);
188     //Es posiciona un iterador apuntant a la primera posició del mapa de distancies\&.
189   //Inv: Farà tantes iteracions fins que l'iterador sigui igual al primer que hem buscat\&. Així ens
190   //estalviem bucles innecessaris\&. Aquest bucle elimina la especie demanada del map interior\&.
191   for (map<string,map<string,double>>::iterator it2 = tabla_distancias_cluster\&.begin(); it2 != it; ++it2) {
192       it2->second\&.erase(it2->second\&.find(id));
193     }
194   //Eliminem la especie del mapa gran de la taula de distancies\&.
195   tabla_distancias_cluster\&.erase(it);
196 
197 }
.fi
.SS "double Cjt_clusters::dist_clust (const string & id, const string & id2) const"

.PP
Busca la distància entre els clusters demanats\&. 
.PP
\fBPrecondició\fP
.RS 4
Els dos clusters demanats existeixen\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha retornat la distància entre els clusters\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP Entren per referència constant dos string amb els identificadors dels clusters\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna un double amb la distància que els separa genèticament\&. Retorna -1 si algun dels dos clusters no existeix\&. 
.RE
.PP

.PP
Definició a la línia 26 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
26                                                                         {
27     //Funció per consultar les distancies dins el mapa de 
28     //distancies de clusters\&.
29         map<string,map<string,double>>::const_iterator it = tabla_distancias_cluster\&.find(id);
30       map<string,double>::const_iterator it2 = it->second\&.find(id2);
31       return it2->second;
32 }
.fi
.SS "pair< string, string > Cjt_clusters::min_dist () const"

.PP
Calcula la distancia mínima entre Clusters\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha calculat la distancia entre dos clusters\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Retorna un pair\&. Els dos elements són de tipu string, retorna els identificadors de clusters a menor distancia\&. 
.RE
.PP

.PP
Definició a la línia 35 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
35                                                  {
36     //Es busca els clusters a menor distancia i 
37     //es retorna en una pair els dos clusters\&.
38     double distancia = 101;
39     pair<string,string> dists;
40     for (map<string,map<string,double>>::const_iterator it = tabla_distancias_cluster\&.begin(); it != tabla_distancias_cluster\&.end(); ++it) {
41         for (map<string,double>::const_iterator it2 = it->second\&.begin(); it2 != it->second\&.end(); ++it2) {
42                 if (it2->second < distancia ){
43                 distancia = it2->second;
44                 dists\&.first = it->first;
45                 dists\&.second = it2->first;
46                 }
47             }
48 
49         }
50     return dists;
51 
52 }
.fi
.SS "void Cjt_clusters::inicialitza_clusters (\fBCjt_especies\fP & conjunt, const bool ve_de_func)"

.PP
Inicialitza els clusters del conjunt\&. 
.PP
\fBPrecondició\fP
.RS 4
Existeix un conjunt d'especies\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
Els clusters s'han inicialitzat\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fI\fBCjt_especies\fP\fP Entra un conjunt d'especies per referència\&. 
.br
\fIBool\fP El booleà té una gran importància, si bool = true imprimirà la taula de distàncies entre clusters, en cas que bool = fals, la funció no imprimirà res\&. 
.RE
.PP

.PP
Definició a la línia 57 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
57                                                                                    {
58     //Establim els iteradors del conjunt d'especies per tal de poder fer el bucle
59     //A cada iteració es modifica una string, agafant la id de una especie i es
60     //crea un cluster a partir de la string i la introdueix al mapa de clusters\&.
61     map_clusters\&.clear();
62     tabla_distancias_cluster\&.clear();
63     conjunt\&.inicio(); // Iterador del conjunt d'especies que apunta a la primera posició\&.
64          while (not conjunt\&.final()) { //comprova que l'iterador no apunta al final
65              string x;
66              conjunt\&.actual(x); // La string x agafa el valor del iterador\&.
67              Cluster clust(x);
68              map_clusters\&.insert(make_pair(x, clust));
69              conjunt\&.avanza(); //Avança posició del iterador\&.
70 
71         }
72     //Es crea la taula de distancies a partir del conjunt\&.
73     tabla_dist_clust(conjunt);
74     if (ve_de_func) imprime_tabla_distancias();
75 }
.fi
.SS "void Cjt_clusters::ejecuta_paso_wpgma (const bool & a)"

.PP
Fusiona els clusters que estan a menor distància\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.br
 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha fusionat els clusters\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIbool\&.\fP Si el bool = true, s'imprimeix la taula de distancies entre clusters resultant\&. 
.RE
.PP

.PP
Definició a la línia 78 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
78                                                    {
79     //S'executa el pas wpgma sempre i quan el tamany
80     //del mapa de clusters sigui > 1\&.
81     if (map_clusters\&.size() > 1) {
82     pair<string,string> pair_dist = min_dist(); //pair amb els dos clusters a menor distancia\&.
83     afegeix_especie_clusters(pair_dist); //Es fica els dos clusters i es fusionen en un nou cluster\&.
84     elimina_especie_clusters(pair_dist\&.first); //S'elimina el cluster\&.
85     elimina_especie_clusters(pair_dist\&.second); //S'elimina el cluster\&.
86     if (a) imprime_tabla_distancias();
87     }
88     else cout << "ERROR: num_clusters <= 1" << endl;
89 }
.fi
.SS "void Cjt_clusters::imprime_cluster (string id) const"

.PP
Imprimeix el cluster indicat\&. 
.PP
\fBPrecondició\fP
.RS 4
Existeix el cluster indicat\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha imprès el cluster indicat\&. 
.RE
.PP
\fBParàmetres\fP
.RS 4
\fIstring\fP id 
.RE
.PP

.PP
Definició a la línia 95 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
95                                                   {
96     //Es posa un iterador apuntant al cluster indicat
97     //Si no apunta al final, s'imprimeix, sino surt un missatge d'error\&.
98     map<string,Cluster>::const_iterator it = map_clusters\&.find(id);
99     if (it == map_clusters\&.end()) cout << "ERROR: El cluster " << id << " no existe\&." << endl;
100     else{
101         it->second\&.escriure();
102     }    
103 }
.fi
.SS "void Cjt_clusters::imprime_tabla_distancias () const"

.PP
Imprimeix la taula de distàncies entre clusters\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha imprès totes les distàncies entre clusters\&. 
.RE
.PP

.PP
Definició a la línia 106 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
106                                                   {
107   //Inv: És situa un iterador apuntant a la primera posició del
108   //mapa de distancies\&. Avançarà una posició fins que el punter apunti al final\&.
109   //A cada iteració s'impreix un identificador de especie i s'executa un segon bucle\&.
110   for(map<string,map<string,double>>::const_iterator it = tabla_distancias_cluster\&.begin(); it != tabla_distancias_cluster\&.end(); ++it) {
111     cout << it->first << ":";
112       //Inv: És situa un iterador apuntant a la primera posició del
113     //map interior del map de distancies d'especies\&. Avançarà una posició fins que el punter apunti al final\&.
114     //A cada iteració s'impreix un identificador d'especie del map interior i la distancia respecte les dues especies\&.
115     for (map<string,double>::const_iterator it2 = it->second\&.begin(); it2 != it->second\&.end(); ++it2) {
116         cout << " " << it2->first << " (" << it2->second << ")"; 
117     }
118     cout << endl;
119   }
120 }
.fi
.SS "void Cjt_clusters::imprime_arbol_filogenetico (\fBCjt_especies\fP & conjunt)"

.PP
Imprimeix l'arbre filogenètic\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha imprès l'arbre filogenètic pel canal standart de sortida\&. 
.RE
.PP

.PP
Definició a la línia 123 del fitxer Cjt_clusters\&.cc\&.
.PP
.nf
123                                                                    {
124     //el bool serveix per imprimir cada cop que executem el pas wpgma\&.
125     //fem un bucle fins que només quedi un element al mapa de clusters
126     bool fals = false;
127     inicialitza_clusters(conjunt,fals);
128 
129     if (map_clusters\&.size() != 0) {
130     while (map_clusters\&.size() > 1) {
131         ejecuta_paso_wpgma(fals);
132     }
133     map<string,Cluster>::const_iterator it = map_clusters\&.begin();
134     it->second\&.escriure(); //escriu el cluster resultant\&.
135     }
136     else cout << "ERROR: El conjunto de clusters es vacio\&." << endl;
137 
138 }
.fi
.SH "Documentació de les Dades Membre"
.PP 
.SS "map<string, \fBCluster\fP> Cjt_clusters::map_clusters\fC [private]\fP"

.PP
Mapa on es guarden els clusters resultants\&. La clau es un string i la dada un \fBCluster\fP\&. 
.PP
Definició a la línia 83 del fitxer Cjt_clusters\&.hh\&.
.SS "map<string, map<string, double> > Cjt_clusters::tabla_distancias_cluster\fC [private]\fP"

.PP
Nested map on es guarden les distancies entre clusters\&. És un nested map\&. 
.PP
Definició a la línia 87 del fitxer Cjt_clusters\&.hh\&.

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
