.TH "Cjt_especies.cc" 3 "Dl Mai 18 2020" "Version 18/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cjt_especies.cc \- Còdig de la classe \fBCjt_especies\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripció Detallada"
.PP 
Còdig de la classe \fBCjt_especies\fP\&. 


.PP
Definició al fitxer \fBCjt_especies\&.cc\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
