.TH "Cluster.cc" 3 "Dv Mai 15 2020" "Version 14/05/2020" "Creació d'un arbre filogenètic." \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cluster.cc \- Còdig de la classe \fBCluster\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripció Detallada"
.PP 
Còdig de la classe \fBCluster\fP\&. 


.PP
Definició al fitxer \fBCluster\&.cc\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. a partir del codi font\&.
