.TH "Especie" 3 "Dc Mai 20 2020" "Version v6.3 19/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Especie \- Representa el conjunt de característiques y operacions de les especies\&.  

.SH SYNOPSIS
.br
.PP
.SS "Mètodes públics"

.in +1c
.ti -1c
.RI "\fBEspecie\fP ()"
.br
.RI "Crea una especie sense identificador ni gen\&. "
.ti -1c
.RI "\fBEspecie\fP (const string &gen1)"
.br
.RI "Crea una especie amb el gen i l'identificador indicat\&. "
.ti -1c
.RI "string \fBconsultar_gen\fP () const"
.br
.RI "Retorna el gen de la espècie\&. "
.ti -1c
.RI "double \fBdistancia\fP (const \fBEspecie\fP &esp) const"
.br
.RI "Retorna un double amb la distància entre la especie del paràmetre implícit i la que ha entrat al paràmetre explícit\&. "
.ti -1c
.RI "void \fBescriure\fP () const"
.br
.RI "Escriu la espècie del paràmetre implícit\&. "
.in -1c
.SS "Mètodes Públics Estàtics"

.in +1c
.ti -1c
.RI "static void \fBset_parametro\fP (const int &k_dato)"
.br
.RI "Introdueix el paràmetre k com a static per calcular els k-meros\&. "
.in -1c
.SS "Mètodes Privats"

.in +1c
.ti -1c
.RI "void \fBkmer\fP ()"
.br
.RI "Calcula els kmeros d'una espècie a partir del seu gen\&. "
.in -1c
.SS "Atributs Privats"

.in +1c
.ti -1c
.RI "string \fBgen\fP"
.br
.RI "És el gen de la espècie\&. "
.ti -1c
.RI "map< string, int > \fBk_meros\fP"
.br
.RI "Estructura de dades on guardem els k-meros de la especie\&. "
.in -1c
.SS "Atributs Privats Estàtics"

.in +1c
.ti -1c
.RI "static int \fBk_num\fP"
.br
.RI "Tamany que indica el tamany dels paquets per separar el gen de la especie (kmeros)\&. "
.in -1c
.SH "Descripció Detallada"
.PP 
Representa el conjunt de característiques y operacions de les especies\&. 

Ofereix la posibilitat de calcular la distància entre dues especies, consultar el gen, i escriure el gen\&. Donat que hem d'establir un paràmetre k, tenim la necessitat de crear una constructora d'especie buida per poder introduir la k\&.
.PP
\fBInvariant\fP
.RS 4
Una espècie sempre tindrà el gen de longitud >= k\&. La k serà sempre de longitud > 0\&. 
.RE
.PP

.PP
Definició a la línia 30 del fitxer Especie\&.hh\&.
.SH "Documentació del Constructor i el Destructor"
.PP 
.SS "Especie::Especie ()"

.PP
Crea una especie sense identificador ni gen\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat es una especie sense identificador, gen i kmeros\&. 
.RE
.PP

.PP
Definició a la línia 18 del fitxer Especie\&.cc\&.
.PP
.nf
18                  {
19   Especie::gen = ' ';
20   Especie::k_meros = map<string, int> ();
21 }
.fi
.SS "Especie::Especie (const string & gen1)"

.PP
Crea una especie amb el gen i l'identificador indicat\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat es una especie amb identificador, gen i kmeros\&. 
.RE
.PP

.PP
Definició a la línia 24 del fitxer Especie\&.cc\&.
.PP
.nf
24                                    {
25   Especie::gen = gen1;
26   Especie::kmer();
27 }
.fi
.SH "Documentació de les Funcions Membre"
.PP 
.SS "void Especie::kmer ()\fC [private]\fP"

.PP
Calcula els kmeros d'una espècie a partir del seu gen\&. 
.PP
\fBPrecondició\fP
.RS 4
El paràmetre implícit és un string amb longitud >= k\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha calculat els k-meros i s'han guardat\&. 
.RE
.PP

.PP
Definició a la línia 99 del fitxer Especie\&.cc\&.
.PP
.nf
99                    {
100   // Inv: El recorregut que fa aquest bucle for mai
101   // farà més iteracions que el tamany del gen - k + 1\&.
102   // A cada iteració es crea un string auxiliar on s'aniran actualitzan els caracters un per un\&.
103   for (int i = 0; i < gen\&.size() - Especie::k_num + 1; ++i) {
104     string aux;
105   // Inv: El recorregut que fa aquest segon bucle mai superarà
106   // les k iteracions\&. Hem igualat la j a la i, per anar avançant cada
107   // cop una posició i el bucle farà menys de k_num + i iteracions\&.
108     for (int j = i; j < Especie::k_num + i; ++j) { 
109       aux += gen[j];
110     }
111     // En el mapa de k-meros busquem el kmero que acabem de crear
112     // en la anterior interació\&. Si aquest no existia s'afegeix al mapa\&.
113     // La clau del mapa és el kmer generat i el valor que se l'assigna és el número
114     // de vegades que es repeteix, al ser el primer cop, es posa un 1\&. En cas que el 
115     // kmer ja existis anteriorment, es busca la clau i s'incrementa en 1 el valor\&.
116     map<string,int>::const_iterator it = Especie::k_meros\&.find(aux);
117     if (it == Especie::k_meros\&.end()) Especie::k_meros\&.insert(make_pair(aux, 1));
118     else Especie::k_meros[aux] = it-> second +1;
119   }
120 } 
.fi
.SS "void Especie::set_parametro (const int & k_dato)\fC [static]\fP"

.PP
Introdueix el paràmetre k com a static per calcular els k-meros\&. 
.PP
\fBPrecondició\fP
.RS 4
Hi ha una k al canal d'entrada\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'ha establert la k per calcular els kmeros\&. 
.RE
.PP

.PP
Definició a la línia 30 del fitxer Especie\&.cc\&.
.PP
.nf
30                                              {
31   Especie::k_num = k_dato;
32 }
.fi
.SS "string Especie::consultar_gen () const"

.PP
Retorna el gen de la espècie\&. 
.PP
\fBPrecondició\fP
.RS 4
El parametre implícit té gen\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat és el gen del paràmetre implícit\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
string 
.RE
.PP

.PP
Definició a la línia 38 del fitxer Especie\&.cc\&.
.PP
.nf
38                                    {
39   return Especie::gen;
40 }
.fi
.SS "double Especie::distancia (const \fBEspecie\fP & esp) const"

.PP
Retorna un double amb la distància entre la especie del paràmetre implícit i la que ha entrat al paràmetre explícit\&. 
.PP
\fBPrecondició\fP
.RS 4
Les dues espècies existeixen\&. 
.RE
.PP
\fBPostcondició\fP
.RS 4
El resultat és la distància entre les dues espècies\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
double\&. Distancia genètica entre les dues especies\&. 
.RE
.PP

.PP
Definició a la línia 42 del fitxer Especie\&.cc\&.
.PP
.nf
42                                                   {
43   // Invariant: Situem dos iterador constants al inici dels dos maps de k_meros
44   // Unio i Intersecció és la cuantitat de elements que compleixen la 
45   // condició de que siguin unió o intersecció\&.
46   // Els elements visitats tenen la clau més petita que els altres\&.
47   // El bucle acaba quan un dels dos iteradors apunta al final, mai poden acabar els dos alhora\&.
48 
49   map<string,int>::const_iterator i = Especie::k_meros\&.begin(), k = esp\&.k_meros\&.begin();
50   double unio = 0, interseccio = 0;
51   while (i != Especie::k_meros\&.end() and k != esp\&.k_meros\&.end()) { // Bucle While general per comparar i anar fent la interseccio/unió dels kmeros\&.
52     if (i->first == k->first) {
53       interseccio += min(i->second,k->second);
54       unio +=  max(i->second, k->second);
55       ++i;
56       ++k;      
57     }
58     else if (i->first < k->first) {
59       unio += i->second;
60       ++i;
61     }
62     else {
63       unio += k->second;
64       ++k;
65     }
66   }
67   // Si el iterador i, el del primer mapa de k-meros no ha acabat el recorregut
68   // entra en aquest bucle\&.
69   // Inv: Els elements de i estan ordenats segons la clau en ordre ascendent\&.
70   while (i != Especie::k_meros\&.end()) {
71     unio += i->second;
72     ++i;
73   } 
74   // Si el iterador k, el del segon mapa de k-meros no ha acabat el recorregut
75   // entra en aquest bucle\&.
76   // Inv: Els elements de k estan ordenats segons la clau en ordre ascendent\&.
77   while (k != esp\&.k_meros\&.end()) { 
78     unio += k->second;
79     ++k;
80   }
81   return (((1-(interseccio/unio))*100));  
82 }
.fi
.SS "void Especie::escriure () const"

.PP
Escriu la espècie del paràmetre implícit\&. 
.PP
\fBPrecondició\fP
.RS 4
Cert 
.RE
.PP
\fBPostcondició\fP
.RS 4
S'han escrit els atributs del parametre implícit al canal estandard de sortida\&. 
.RE
.PP

.PP
Definició a la línia 91 del fitxer Especie\&.cc\&.
.PP
.nf
91                              {
92   cout << Especie::gen << endl;
93 }
.fi
.SH "Documentació de les Dades Membre"
.PP 
.SS "string Especie::gen\fC [private]\fP"

.PP
És el gen de la espècie\&. 
.PP
Definició a la línia 35 del fitxer Especie\&.hh\&.
.SS "int Especie::k_num\fC [static]\fP, \fC [private]\fP"

.PP
Tamany que indica el tamany dels paquets per separar el gen de la especie (kmeros)\&. 
.PP
Definició a la línia 38 del fitxer Especie\&.hh\&.
.SS "map<string, int> Especie::k_meros\fC [private]\fP"

.PP
Estructura de dades on guardem els k-meros de la especie\&. 
.PP
Definició a la línia 41 del fitxer Especie\&.hh\&.

.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
