.TH "Especie.cc" 3 "Dt Mai 19 2020" "Version v6.3 19/05/2020" "Creació d'un arbre filogenètic. Xavier Coll Ribas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Especie.cc \- Còdig de la classe \fBEspecie\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripció Detallada"
.PP 
Còdig de la classe \fBEspecie\fP\&. 


.PP
Definició al fitxer \fBEspecie\&.cc\fP\&.
.SH "Autor"
.PP 
Generat automàticament per Doxygen per a Creació d'un arbre filogenètic\&. Xavier Coll Ribas a partir del codi font\&.
